event_organizer/urls.py
from django.urls import path

from . import views

app_name = 'event_organizer'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('delete/', views.delete, name="delete"),
    path('', views.index, name='index'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include
import event_organizer.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event_organizer.urls'))
]

event_organizer/models.py
from django.db import models

# Create your models here.
class Event(models.Model) :
    name = models.CharField(max_length=128)

    def __str__(self) :
        return self.name

class Participant(models.Model) :
    name = models.CharField(max_length=128)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self) :
        return str(self.event) + " - " + self.name

event_organizer/forms.py
from django import forms  
from .models import *

class EventForm(forms.ModelForm) :
    class Meta :
        model = Event
        fields = '__all__'

class ParticipantForm(forms.ModelForm) :
    class Meta :
        model = Participant
        fields = '__all__'

event_organizer/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from .forms import *
from .models import *

def index (request) :
    events = Event.objects.all()
    participants = Participant.objects.all()

    ev_par = []
    for event in events :
        event_participant = []
        for participant in participants :
            if (str(participant.event) == str(event)) :
                event_participant.append(participant)
        ev_par.append((event, event_participant))   

    context = {
        "events" : ev_par,
    }
    return render(request, 'index.html', context)

def register (request) :
    event_id = request.POST.get('event_id', None)
    participant_name = request.POST.get('participant_name', None)

    event_name = request.POST.get('event_name', None)

    if(event_id and participant_name) :
        Participant.objects.create(
            name=participant_name,
            event=Event.objects.get(id=event_id)
        )
    else :
        Event.objects.create(name=event_name)

    return redirect(reverse('event_organizer:index'))

def delete (request) :
    user_id = request.POST.get('user_id', None)
    participant = Participant.objects.get(id=user_id)

    participant.delete()
    return redirect(reverse('event_organizer:index'))

event_organizer/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <title>Story 6 </title>
</head>
<body>
  <div class="d-flex flex-row flex-wrap">
    {% for event in events %}
    <div class="card p-3">
      <h5 class="display-5">{{ event.0.name }}</h5>
      <ul>
        {% for participant in event.1 %}
          <li>{{ participant.name }}
            <form action="{% url 'event_organizer:delete' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="user_id" value={{participant.id}}>
              <button class="btn btn-danger righty" type="submit">X</button>
            </form></li>   

        {% endfor %}
      </ul>
      <button class="btn btn-primary my-btn" data-toggle="modal" data-target="#addParticipant{{ event.0.id }}">Daftar!!!</button>

      <!-- Modal -->
      <div class="modal fade" id="addParticipant{{ event.0.id }}" tabindex="-1" role="dialog" aria-labelledby="addParticipantTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="addParticipantTitle">Daftar ke acara "{{ event.0.name }}"?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="{% url 'event_organizer:register' %}" method="post">
              <div class="modal-body">
                {% csrf_token %}
                <input type="hidden" name="event_id" value="{{ event.0.id }}">
                <label for="participant_name">Nama : </label>
                <input id="participant_name" name="participant_name" type="text" autofocus>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Gajadi</button>
                <button type="submit" class="btn btn-primary">Daftar</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <div class="card my-auto">
      <button class="btn btn-primary p-3 text-align-center my-auto" data-toggle="modal" data-target="#addEvent">Tambah Event!!!</button>

       <div class="modal fade" id="addEvent" tabindex="-1" role="dialog" aria-labelledby="addEventTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="addEventTitle">Buat acara baru"?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="{% url 'event_organizer:register' %}" method="post">
              <div class="modal-body">
                {% csrf_token %}
                <label for="event_name">Nama Acara : </label>
                <input id="event_name" name="event_name" type="text" autofocus>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Gajadi</button>
                <button type="submit" class="btn btn-primary">Buat</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script>
    $(document).on('shown.bs.modal', '.modal', function () {
      $(this).find('[autofocus]').focus();
    });
  </script>
</body>
</html>